name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install project dependencies
        run: npm install

      - name: Start server
        run: npm start & # стартиране във фонов режим с &
        env:
          NODE_ENV: test

      - name: Wait for server to be up
        run: npx wait-on http://localhost:8080 #npx wait-on wait for http://localhost:8080

      - name: Run unit test for the application
        run: npm run test:unit

      - name: gogata05
        run: echo 'georgi.markov'

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Wait for deployment to complete
        run: sleep 60

  run-ui-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install project dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Run UI test for the application
        run: npm run test:ui
